name: linux-x64-cpu-clang
on: [push, pull_request]
jobs:
  linux-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: Tencent/ncnn
        submodules: true
    - name: update
      run: sudo apt-get update
    - name: protobuf
      run: sudo apt-get install libprotobuf-dev protobuf-compiler libopencv-dev
    - name: configure
      env:
        CC: clang
        CXX: clang++
      run: mkdir build && cd build && cmake -DNCNN_BUILD_TESTS=ON ..
    - name: build
      run: cmake --build build -j 2
    - name: test
      run: cd build && ctest --output-on-failure -j 2

          
    - name: uploadexe
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: finaa.7z
        path: /home/runner/work/lunusbuild/lunusbuild/build
